### ISSUE TITLE
`cells` is a `dict`?

### ISSUE THREAD

**Issue by kolayne** [mineserver228/WaveFunctionCollapse#4]
`cells` is a dictionary with its keys, apparently, being consecutive integer values starting with 0 (because the only place I found where you assign new values looks like `cells[len(cells.keys())] = something` (btw, equivalent to `cells[len(cells)] = something`). So, why not just make it a list?

**Comment by mineserver228** [comment]
Has been fixed in commit Grid optimization, bug fix and code restructuring on #3 branch
